[build]
  functions = "netlify/functions"

[functions]
  # Increase timeout for claude-proxy function
  timeout = 26

[functions."claude-proxy"]
  # Specific timeout for claude-proxy function (max 26 seconds for Pro plans, 10 for free)
  timeout = 26

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"

# Optional: Redirect rules (if needed)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
